name: finsight-ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.1.4
  - numpy=1.26.2
  - pytest=7.4.3
  - black=23.12.1
  - streamlit=1.29.0
  - pip=23.3.1
  - pip:
    - fastapi>=0.104.0
    - uvicorn>=0.24.0
    - PyPDF2>=3.0.0
    - pdfplumber>=0.10.0
    - openai>=1.3.0
    - langchain>=0.0.350
    - sentence-transformers>=2.2.2
    - pinecone>=2.2.4
    - google-cloud-bigquery>=3.13.0
    - google-cloud-storage>=2.13.0
    - python-dotenv>=1.0.0
    - isort>=5.12.0 